apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-axhy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-axhy
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-axhy
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-axhy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-axhy
    spec:
      containers:
      - image: quay.io/qijing/ex-registry-bzpb-tenant/appstudio/dc-metro-map-axhy@sha256:bea2b2b95591fd735602919e54d1edbf3eaa0b94bcdf39050b772f87a0353712
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
